---
title: "From Frequentist Problems Towards Bayesian Solutions"
subtitle: "Part 2: (JASPを使っての)ベイズ統計入門"
author: "Jorge N. Tendeiro"
date: "10 August 2019<br><br>Slides at: [https://rebrand.ly/Nagoya2019-Part2-JP](https://rebrand.ly/Nagoya2019-Part2-JP)<br>GitHub: [https://github.com/jorgetendeiro/Nagoya-Workshop-10-Aug-2019 ](https://github.com/jorgetendeiro/Nagoya-Workshop-10-Aug-2019)"
# https://jorgetendeiro.github.io/Nagoya-Workshop-10-Aug-2019/Nagoya-10-Aug-2019-Part2  -JP.html
output: 
  ioslides_presentation:
    smaller: true
    widescreen: true
    transition: .4
    css: [style/slides.css, style/toc-style.css]
    includes:
      in_header: style/TOC_generator.js.wrapper
bibliography: references.bib
csl: style/apa-old-doi-prefix.csl
---

```{r setup, include = FALSE, fig.align = 'center'}
knitr::opts_chunk$set(
  echo      = FALSE, 
  fig.cap   = '', 
  out.extra = 'style="background-color: #000000; padding:5px; display:block; margin:auto;"'
  ) 
```

<!-- To print to PDF, run: 
pagedown::chrome_print("Nagoya-10-Aug-2019-Part2.html")
-->

## Today
<!-- add div element table of content for javascript to fill -->
<div id="toc"></div>

# Suggested reading material<br>参考文献 {.section}

## ベイズ統計入門{.build}
<span style="color:green">Papers:</span>

- @etz2018: The "Harry Potter" paper.<br>
例えが含まれていて*とても* 読みやすいイントロダクション.
- @etz2018a: "How to become a Bayesian in eight easy steps: An annotated reading list".<br>
Alexander Etz氏は*とても*読みやすい論文が多いです. 時間はかなり要しますが、この論文を強くお勧めします.
- @kruschke2013: ベイズ統計の軸となるコンセプトへのわかりやすい導入に加えて、"検定"vs"推定"についての議論が展開されています.この点におけるKruschke氏の意見を個人的に支持しています.

<span style="color:green">Books:</span>

- @kruschke2015: The "puppies" book.<br>
初心者でもわかりやすい本で多くの例と分析コードが載せられています.　ベイズ統計初心者には最適の本です.
- @mcelreath2016: 私が読んだ限りでは、この本は素晴らしいです.
- @lambert2018: まだ半分程しか読めていませんが、ベイズ統計を教えるには最適な本だと思います.
- @gelman2014: 上級者向きの本(おそらく初心者向きではないと思います). 名作である事は確かです.

## JASPについて学ぶ {.build}

<span style="color:green">Website</span><br> [https://jasp-stats.org/how-to-use-jasp/](https://jasp-stats.org/how-to-use-jasp/).<br>
このサイトには以下の内容が含まれている:

- [Tutorial section](https://jasp-stats.org/how-to-use-jasp/)
- [YouTube channel](http://www.youtube.com/channel/UCSulowI4mXFyBkw3bmp7pXg) 動画で学ぶことができる.
- [Forum](http://forum.cogsci.nl/index.php?p=/categories/jasp-bayesfactor)　問題が自分では解決できない時に質問することができる.
- [Teaching with JASP](https://jasp-stats.org/teaching-with-jasp/) より多くの教材が含まれている.

<br>
<span style="color:green">Video tutorials</span><br>
Etz氏らは新しいビデオを随時追加している.<br>
[https://alexanderetz.com/jasp-tutorials/](https://alexanderetz.com/jasp-tutorials/).

<br>
<span style="color:green">Papers</span>

- @marsman2017[, in *European Journal of Developmental Psychology*].
- @wagenmakers2018[, in a special issue in *Psychonomic Bulletin & Review*].

# Frequentist *versus* Bayes<br>頻度論VSベイズ {.section}
## Frequentist paradigm(頻度論パラダイム) {.build}
<span style="color:green">確率</span>の概念:

- <span style="color:red">procedure(手順)</span>をlong-run (無限回) 繰り返すことを想定した頻度.

> The probability of a fair coin landing up heads is 50%.

- 無限回を想定した連続の中では、一つの事象については何も結論づけることができない.

> What is the probability that the <span style="color:red">next</span> coin toss lands heads?

- <span style="color:red">$p$-値</span> と <span style="color:red">信頼区間</span>について思い出して下さい:
これらは両方とも、無限回を想定した頻度に基づいている.<br>
<span style="color:green">結論:</span>１つの$p$-値または信頼区間から果たして何を結論づけられるのでしょうか？...

## Bayesian paradigm(ベイジアンパラダイム) {.build}
<span style="color:green">確率</span>の概念:

- 信念の度合い.
- 実相(true state of affairs)についての不確定性を表すもの.
- 主観的: 各自、それぞれの信念をもっている.
- 各自の信念を*確率の法則*にしたがってアップデートするためにデータが使われる.
- 一回の事象または反復される事象の両方ともに適用される.

<br>
でも、どうやって我々の信念をデータをもとにアップデートすれば良いのでしょう？

# Bayes' rule<br>ベイズの規則 {.section}

## Bayes' rule (ベイズの規則){.build}
$\mathcal{A}$を「私たちが研究したい何か」としましょう.
<br>
例えば:

- パラメーター(母集団の平均値$\mu$等).
- 仮説($\mu > 100$等).

Bayes' rule(ベイズの規則):

<p align="center"><span style="color:green">
$p(\mathcal{A}|\text{data}) = \frac{p(\mathcal{A})p(\text{data}|\mathcal{A})}{p(\text{data})}$
</span></p>

- $p(\mathcal{A})$: <span style="color:red">Prior</span> probability(事前確率).
- $p(\text{data}|\mathcal{A})$: Data <span style="color:red">likelihood</span> (データ尤度).
- $p(\text{data})$: Marginal likelihood (周辺尤度 ).
- $p(\mathcal{A}|\text{data})$: <span style="color:red">Posterior</span> probability(事後確率).

## Bayes' rule and frequentism <br>(ベイズの規則と頻度論)
<span style="color:red">重要:</span>

- ベイズの規則は数学的に証明されたものであり、当然、確率の原理に従っている.
- 頻度論はこの公式については異議を唱えていない!

## ベイズの規則とモデル比較{.build}
例えば、私たちが<span style="color:red"> ２つの</span>競合する仮説($\mathcal{H}_0$ と $\mathcal{H}_1$)を持っているとします.

ここでベイズの規則を両方の仮説($\mathcal{H}_0$ と $\mathcal{H}_1$)に適用することができる:

<p align="center">
$p(\mathcal{H}_0|\text{data}) = \frac{p(\mathcal{H}_0)p(\text{data}|\mathcal{H}_0)}{p(\text{data})}
\quad,\quad
p(\mathcal{H}_1|\text{data}) = \frac{p(\mathcal{H}_1)p(\text{data}|\mathcal{H}_1)}{p(\text{data})}$.
</p>

次に両方の方程式を割る:

<p align="center"><span style="color:green">
$\underset{\text{Posterior odds}}{\underbrace{\frac{p(\mathcal{H}_0|\text{data})}{p(\mathcal{H}_1|\text{data})}}} =
\underset{\text{Prior odds}}{\underbrace{\frac{p(\mathcal{H}_0)}{p(\mathcal{H}_1)}}}
\times
\underset{BF_{01}}{\underbrace{\frac{p(\text{data}|\mathcal{H}_0)}{p(\text{data}|\mathcal{H}_1)}}}$
</span></p>

この$BF_{01}$が<span style="color:red">ベイズ因子(Bayes factor)</span>と呼ばれるものである.

ベイズ因子はデータによって得られる両仮説の*相対的な証拠*の指標である.<br>
E.g., 例えば$BF_{01} = 5$であれば:

- $\mathcal{H}_0$よりも$\mathcal{H}_1$の下でデータが得られた可能性が５倍高い.
- データを基に、我々は$\mathcal{H}_0$を$\mathcal{H}_1$の５倍支持する.

## Bayes factor(ベイズ因子)
ベイズ因子に関しては多くの事を言う事ができます.

ベイズ因子の熱烈なフォロワーがいます[e.g., @kass1995; @dienes2014; @morey2016b; @wagenmakers2018a].

しかし、私を含め、批判的な意見もあります[@tendeiro2019a].

# JASP {.section}

## 注意書き

JASPはベイズ因子を重視している.

個人的に私はパラメーター推定を行う方がより明瞭で包括的な枠組みだと思うので、ベイズ因子を好ましいと思いません.

- 私が何故そう思うのかについてはこちらの事前登録された論文をご覧下さい: @kiers2019a.

## 問題例
さぁ、JASPを始めてみましょう！

手始めに、この第一実験を例として使いましょう @bem2011:

<p align="center"><span style="color:green">Precognitive detection of erotic stimuli(性的刺激の予知的検出)</span>.</p>

- $n = 100$ (男性50名, 女性50名), 各自36試行.
- 各試行:
    - ２つのカーテンが隣同士にパソコンのスクリーンに提示される.
    - １つのカーテンは写真を隠し、もう一方は黒い壁を隠す.
    - 性的な写真と性的でない写真をランダムに混ぜる.

主な研究仮定:

> Subjects are able to "feel" where the erotic pictures are more often than chance (!!!).

## Bem教授による結果の一部 (2011)

> Across all 100 sessions, participants correctly identified the future position of the erotic pictures significantly more frequently than the 50% hit rate expected by chance: 53.1%, $t(99) = 2.51$, $p = .01$, $d = 0.25$. In contrast, their hit rate on the nonerotic pictures did not differ significantly from chance: 49.8%, $t(99) = -0.15$, $p = .56$.

> The difference between erotic and nonerotic trials was itself significant, $t_\text{diff}(99) = 1.85$, $p = .031$, $d = 0.19$.

> (...) the correlation between stimulus seeking and psi performance was .18 ($p = .035$).



<style type="text/css">
slides > slide { overflow: scroll; }
}
</style>

# References {.section}

----
